- hosts: all
  remote_user: user
  become: yes
    #  become_user: secadm
  tasks:
    - name: find all files that are older than 30 days
      find:
        paths: /var/log
        age: 30d
        recurse: yes
      register: filesOlderThan10
    - name: remove older than 10
      file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ filesOlderThan10.files }}"
